- hosts: all
  become: true
  tasks:
    - name: update repository index (Ubuntu)
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: install apache2 package (Ubuntu)
      apt:
        name: apache2
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: add PHP support for apache (Ubuntu)
      apt:
        name: libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install apache and php package (CentOS)
      yum:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "CentOS"
