- hosts: db_servers
  become: true
  tasks:
    - name: Install MariaDB package (CentOS)
      yum:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "CentOS"

    - name: Install MariaDB package (Ubuntu)
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: "MariaDB - Restarting/Enabling"
      service:
        name: mariadb
        state: restarted
        enabled: true
